version: '3'
services:
  influxdb:
    hostname: influxdb
    container_name: influxdb
    image: influxdb
    volumes:
      - config-influxdb:/var/lib/influxdb
    restart: unless-stopped

  varken:
    hostname: varken
    container_name: varken
    image: boerderij/varken
    volumes:
      - config-varken:/config
    env_file: .env
    environment:
      - TZ=America/New_York
    depends_on:
      - influxdb
    restart: unless-stopped

  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - config-grafana:/config
    environment:
      - GF_PATHS_DATA=/config/data
      - GF_PATHS_LOGS=/config/logs
      - GF_PATHS_PLUGINS=/config/plugins
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    depends_on:
      - influxdb
      - varken
    restart: unless-stopped


volumes:
  config_influxdb:
  config_varken:
  config_grafana:
